title: 一个风向的Blog

# 自定义post url
permalink: /:year/:month/:day/:title
timezone: Asia/Shanghai

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

markdown: kramdown
kramdown:
    input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
    extensions:
    - autolink
    - footnotes
    - smart
hard_wrap: false
#  use_coderay: true
syntax_highlighter: rouge
#  coderay:
#  coderay_line_numbers:  nil

# White-listed plugins
gems:
  - jekyll-sitemap

production_url: http://raoliangblog.com
github_url: https://github.com/lanffy
weibo_url: http://weibo.com/raoliang
theme: jekyll-theme-cayman